name: Update Relics HTML

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: pip install requests beautifulsoup4

    - name: Rodar o script
      run: python relic_extractor.py

    - name: Commit e push do HTML gerado
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "Relic Bot"
        git config user.email "bot@example.com"
        git add output/relics.html
        git commit -m "Atualização automática das relíquias" || echo "Sem mudanças"
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
