name: Atualizar Relíquias

on:
  workflow_dispatch:            # Rodar manualmente
  schedule:
    - cron: '0 12 * * 1'         # Toda segunda-feira às 12h UTC (9h Brasília)
    - cron: '0 12 15 * *'        # Dia 15 de cada mês às 12h UTC (backup)

jobs:
  update-relics:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: pip install beautifulsoup4 requests

    - name: Executar script
      run: python relic_extractor.py

    - name: Garantir alteração mínima
      run: |
        date +"Última execução: %d/%m/%Y %H:%M:%S UTC" > last_run.txt

    - name: Commit e Push
      run: |
        git config user.name "Relic Bot"
        git config user.email "relic-bot@users.noreply.github.com"
        git add output/relics.html last_run.txt
        git commit -m "Atualização automática das relíquias" || echo "Nada a commitar"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git main
        git add output/relics.html
        git commit -m "Atualização automática das relíquias" || echo "Nada a commitar"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git main
